server.port=7789
spring.datasource.url=jdbc:postgresql://localhost:5432/jnotifier
spring.datasource.username=postgres
spring.datasource.password=1234567890

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# App Properties
jnotifier.app.jwtSecret=YTI5YjNkNGU1ZjZnN2g4aTljM2Q0ZTVmNmc3aDhpOWMzZDRlNWY2ZzdoOGk5YzNkNGU1ZjZnN2g4aTljM2Q0ZTVmNmc3aDhpOWM=
jnotifier.app.jwtExpirationMs=3600000
jnotifier.app.jwtRefreshExpirationMs=86400000
jnotifier.notification.max-attempts=3
jnotifier.app.default-otp-enabled=true